export const products = [
    {
        id: 1,
        title: "Vel elit euismod",
        price: 26.0,
        oldPrice: 42.0,
        image: "/images/Products-images/product-1.png",
        colors: ["#EEFF61", "#F3559A", "#755BF9"],
    },
    {
        id: 2,
        title: "Ultricies condimentum imperdiet",
        price: 26.0,
        oldPrice: 42.0,
        image: "/images/Products-images/product-2.png",
        colors: ["#EEFF61", "#F3559A", "#755BF9"],
    },
    {
        id: 3,
        title: "Vitae suspendisse sed",
        price: 26.0,
        oldPrice: 42.0,
        image: "/images/Products-images/product-3.png",
        colors: ["#EEFF61", "#F3559A", "#755BF9"],
    },
    {
        id: 4,
        title: "Sed at fermentum",
        price: 26.0,
        oldPrice: 42.0,
        image: "/images/Products-images/product-4.png",
        colors: ["#EEFF61", "#F3559A", "#755BF9"],
    },
    {
        id: 5,
        title: "Fusce pellentesque at",
        price: 26.0,
        oldPrice: 42.0,
        image: "/images/Products-images/product-5.png",
        colors: ["#EEFF61", "#F3559A", "#755BF9"],
    },
    {
        id: 6,
        title: "Vestibulum magna laoreet",
        price: 26.0,
        oldPrice: 42.0,
        image: "/images/Products-images/product-6.png",
        colors: ["#EEFF61", "#F3559A", "#755BF9"],
    },
    {
        id: 7,
        title: "Sollicitudin amet orci",
        price: 26.0,
        oldPrice: 42.0,
        image: "/images/Products-images/product-7.png",
        colors: ["#EEFF61", "#F3559A", "#755BF9"],
    },
    {
        id: 8,
        title: "Ultrices mauris sit",
        price: 26.0,
        oldPrice: 42.0,
        image: "/images/Products-images/product-8.png",
        colors: ["#EEFF61", "#F3559A", "#755BF9"],
    },
    {
        id: 9,
        title: "Pellentesque condimentum ac",
        price: 26.0,
        oldPrice: 42.0,
        image: "/images/Products-images/product-9.png",
        colors: ["#EEFF61", "#F3559A", "#755BF9"],
    },
    {
        id: 10,
        title: "Cras scelerisque velit",
        price: 26.0,
        oldPrice: 42.0,
        image: "/images/Products-images/product-10.png",
        colors: ["#EEFF61", "#F3559A", "#755BF9"],
    },
    {
        id: 11,
        title: "Lectus vulputate faucibus",
        price: 26.0,
        oldPrice: 42.0,
        image: "/images/Products-images/product-11.png",
        colors: ["#EEFF61", "#F3559A", "#755BF9"],
    },
    {
        id: 12,
        title: "Purus risus, ut",
        price: 26.0,
        oldPrice: 42.0,
        image: "/images/Products-images/product-12.png",
        colors: ["#EEFF61", "#F3559A", "#755BF9"],
    },
    
];
